In [21]:
import pandas as pd

In [22]:
fin = pd.read_csv("C:\Datahack\dirty data 2\jin.csv")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\karti\AppData\Local\Temp\ipykernel_25244\3944336840.py:1: SyntaxWarning: invalid escape sequence '\D'
  fin = pd.read_csv("C:\Datahack\dirty data 2\jin.csv")
C:\Users\karti\AppData\Local\Temp\ipykernel_25244\3944336840.py:1: DtypeWarning: Columns (5,6,7,8,18) have mixed types. Specify dtype option on import or set low_memory=False.
  fin = pd.read_csv("C:\Datahack\dirty data 2\jin.csv")

In [23]:
fin2 = pd.read_csv("C:\Datahack\dirty data 2\jin2.csv")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\karti\AppData\Local\Temp\ipykernel_25244\144492359.py:1: SyntaxWarning: invalid escape sequence '\D'
  fin2 = pd.read_csv("C:\Datahack\dirty data 2\jin2.csv")

In [5]:
fin2.head()

,id,callsign,flighthistory_id,latitude,longitude,asdiflightplan_id
0,108923851,SWA546,308536681,32.0,-106.5,114142575
1,108923851,SWA546,308536681,32.0,-106.5,114144129
2,108923851,SWA546,308536681,32.0,-106.5,114145255
3,108923851,SWA546,308536681,32.0,-106.5,114153741
4,108923851,SWA546,308536681,32.0,-106.5,114182481

In [6]:
fin['flighthistory_id'] = fin['id']

In [10]:
idk = pd.merge(fin, fin2, on='flighthistory_id', how='inner')
idk.head()

,id_x,airline_icao_code,flight_number,departure_airport_code,arrival_airport_code,scheduled_gate_departure,actual_gate_departure,scheduled_gate_arrival,actual_gate_arrival,scheduled_runway_departure,...,departure_airport_timezone_offset,arrival_airport_timezone_offset,scheduled_aircraft_type,icao_aircraft_type_actual,flighthistory_id,id_y,callsign,latitude,longitude,asdiflightplan_id
0,305968035,SNC,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,...,-7,-7,SH6,NaN,305968035,187720467,SNC1327,37.65,-122.35,114255346
1,305913323,USC,608,DAY,LUK,2013-08-14 20:30:00+00:00,NaN,2013-08-15 09:35:00+00:00,NaN,NaN,...,-4,-4,CNC,NaN,305913323,191253363,USC608,44.75,-92.90,114217184
2,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,...,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114320179
3,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,...,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114321056
4,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,...,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114321973

In [11]:
idk.shape

(5251990, 26)

In [15]:
idk.head()

,id_x,airline_icao_code,flight_number,departure_airport_code,arrival_airport_code,scheduled_gate_departure,actual_gate_departure,scheduled_gate_arrival,actual_gate_arrival,scheduled_runway_departure,...,departure_airport_timezone_offset,arrival_airport_timezone_offset,scheduled_aircraft_type,icao_aircraft_type_actual,flighthistory_id,id_y,callsign,latitude,longitude,asdiflightplan_id
0,305968035,SNC,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,...,-7,-7,SH6,NaN,305968035,187720467,SNC1327,37.65,-122.35,114255346
1,305913323,USC,608,DAY,LUK,2013-08-14 20:30:00+00:00,NaN,2013-08-15 09:35:00+00:00,NaN,NaN,...,-4,-4,CNC,NaN,305913323,191253363,USC608,44.75,-92.90,114217184
2,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,...,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114320179
3,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,...,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114321056
4,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,...,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114321973

In [16]:
pd.set_option('display.max_columns', None)

In [17]:
idk.head()

,id_x,airline_icao_code,flight_number,departure_airport_code,arrival_airport_code,scheduled_gate_departure,actual_gate_departure,scheduled_gate_arrival,actual_gate_arrival,scheduled_runway_departure,actual_runway_departure,scheduled_runway_arrival,actual_runway_arrival,creator_code,scheduled_air_time,scheduled_block_time,departure_airport_timezone_offset,arrival_airport_timezone_offset,scheduled_aircraft_type,icao_aircraft_type_actual,flighthistory_id,id_y,callsign,latitude,longitude,asdiflightplan_id
0,305968035,SNC,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,NaN,NaN,NaN,I,NaN,63.0,-7,-7,SH6,NaN,305968035,187720467,SNC1327,37.65,-122.35,114255346
1,305913323,USC,608,DAY,LUK,2013-08-14 20:30:00+00:00,NaN,2013-08-15 09:35:00+00:00,NaN,NaN,NaN,NaN,NaN,I,NaN,785.0,-4,-4,CNC,NaN,305913323,191253363,USC608,44.75,-92.90,114217184
2,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,NaN,NaN,NaN,I,NaN,245.0,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114320179
3,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,NaN,NaN,NaN,I,NaN,245.0,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114321056
4,305923831,USC,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,NaN,NaN,NaN,I,NaN,245.0,-4,-5,PA2,NaN,305923831,191292031,USC8O1,27.95,-82.35,114321973

In [19]:
idk['creator_code'].value_counts()

creator_code
I    4838016
A     345095
D      68879
Name: count, dtype: int64

In [ ]:
idk.drop(columns=['id_x','id_y','airline_icao_code','creator_code'],axis=1,inplace=True)

In [26]:
fin3 = pd.read_csv("C:\Datahack\dirty data 2\jin4.csv")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\karti\AppData\Local\Temp\ipykernel_25244\481752556.py:1: SyntaxWarning: invalid escape sequence '\D'
  fin3 = pd.read_csv("C:\Datahack\dirty data 2\jin4.csv")

In [27]:
fin3.head()

,Unnamed: 0,id,asdiflightplan_id,ordinal,airway,center,fix,latitude,longitude,sector
0,208,300,114132888,1,EAU9,ZDC,J89,39.783333,-75.050000,ZLCBOI
1,209,301,114132889,0,CRSON2,ZJX,SOONE,39.783333,-75.000000,ZLC31
2,210,302,114132889,1,RACYR1,ZMA,ICBOD,39.783333,-74.966667,ZLC41
3,211,303,114132890,O,J73,ZLA,OTK,39.783333,-74.966667,ZLC42
4,212,304,114132890,1,FOOXX3,ZDV,HITTR,39.783333,-74.950000,ZLCUTT

In [29]:
fin3.drop(columns=['Unnamed: 0','id','latitude','longitude'],axis=1,inplace=True)

In [63]:
idk2 = pd.merge(idk, fin3, on='asdiflightplan_id', how='inner')

In [ ]:
idk2.to_csv('idk2.csv', index = False)

In [58]:
idk2.shape

(3664986, 27)

In [59]:
idk2.head()

,flight_number,departure_airport_code,arrival_airport_code,scheduled_gate_departure,actual_gate_departure,scheduled_gate_arrival,actual_gate_arrival,scheduled_runway_departure,actual_runway_departure,scheduled_runway_arrival,actual_runway_arrival,scheduled_air_time,scheduled_block_time,departure_airport_timezone_offset,arrival_airport_timezone_offset,scheduled_aircraft_type,icao_aircraft_type_actual,flighthistory_id,callsign,latitude,longitude,asdiflightplan_id,ordinal,airway,center,fix,sector
0,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,63.0,-7,-7,SH6,NaN,305968035,SNC1327,37.65,-122.35,114255346,O,HAROB4,CZY,NEALS,ZAB71
1,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,63.0,-7,-7,SH6,NaN,305968035,SNC1327,37.65,-122.35,114255346,1,Q1,ZOB,BKW,ZKC23
2,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,63.0,-7,-7,SH6,NaN,305968035,SNC1327,37.65,-122.35,114255346,2,GOLDN6,ZBW,ASBUR,ZKC06
3,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,245.0,-4,-5,PA2,NaN,305923831,USC8O1,27.95,-82.35,114321973,0,KENLN3,ZFW,RABOW,ZMPOMA
4,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,245.0,-4,-5,PA2,NaN,305923831,USC8O1,27.95,-82.35,114321973,1,SSCOT1,ZNY,VXV,ZDCJR1

In [60]:
idk2.head()

,flight_number,departure_airport_code,arrival_airport_code,scheduled_gate_departure,actual_gate_departure,scheduled_gate_arrival,actual_gate_arrival,scheduled_runway_departure,actual_runway_departure,scheduled_runway_arrival,actual_runway_arrival,scheduled_air_time,scheduled_block_time,departure_airport_timezone_offset,arrival_airport_timezone_offset,scheduled_aircraft_type,icao_aircraft_type_actual,flighthistory_id,callsign,latitude,longitude,asdiflightplan_id,ordinal,airway,center,fix,sector
0,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,63.0,-7,-7,SH6,NaN,305968035,SNC1327,37.65,-122.35,114255346,O,HAROB4,CZY,NEALS,ZAB71
1,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,63.0,-7,-7,SH6,NaN,305968035,SNC1327,37.65,-122.35,114255346,1,Q1,ZOB,BKW,ZKC23
2,1327,SFO,SMF,2013-08-14 14:37:00+00:00,NaN,2013-08-14 15:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,63.0,-7,-7,SH6,NaN,305968035,SNC1327,37.65,-122.35,114255346,2,GOLDN6,ZBW,ASBUR,ZKC06
3,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,245.0,-4,-5,PA2,NaN,305923831,USC8O1,27.95,-82.35,114321973,0,KENLN3,ZFW,RABOW,ZMPOMA
4,801,FWA,STP,2013-08-14 23:00:00+00:00,NaN,2013-08-15 03:05:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,245.0,-4,-5,PA2,NaN,305923831,USC8O1,27.95,-82.35,114321973,1,SSCOT1,ZNY,VXV,ZDCJR1

In [61]:
idk2.shape

(3664986, 27)

In [62]:
idk2.drop_duplicates

KeyboardInterrupt:

In [44]:
idk2.shape

(3664986, 27)

In [45]:
null_percentages = idk2.isnull().mean() * 100

for column, percentage in null_percentages.items():
    print(f"{column}: {percentage}%")

flight_number: 0.0%
departure_airport_code: 0.0%
arrival_airport_code: 0.0%
scheduled_gate_departure: 6.396231800066904%
actual_gate_departure: 11.379470480924073%
scheduled_gate_arrival: 6.39617722959924%
actual_gate_arrival: 11.17412181110651%
scheduled_runway_departure: 0.12583949843191763%
actual_runway_departure: 0.7944914387121806%
scheduled_runway_arrival: 0.14540301108926473%
actual_runway_arrival: 0.4736170888510897%
scheduled_air_time: 0.14540301108926473%
scheduled_block_time: 6.396231800066904%
departure_airport_timezone_offset: 0.0%
arrival_airport_timezone_offset: 0.0%
scheduled_aircraft_type: 8.044560061075268%
icao_aircraft_type_actual: 1.2481084511646157%
flighthistory_id: 0.0%
callsign: 0.0%
latitude: 0.0%
longitude: 0.0%
asdiflightplan_id: 0.0%
ordinal: 0.0%
airway: 0.0%
center: 0.0%
fix: 0.0%
sector: 0.0%

In [46]:
idk2.columns

Index(['flight_number', 'departure_airport_code', 'arrival_airport_code',
       'scheduled_gate_departure', 'actual_gate_departure',
       'scheduled_gate_arrival', 'actual_gate_arrival',
       'scheduled_runway_departure', 'actual_runway_departure',
       'scheduled_runway_arrival', 'actual_runway_arrival',
       'scheduled_air_time', 'scheduled_block_time',
       'departure_airport_timezone_offset', 'arrival_airport_timezone_offset',
       'scheduled_aircraft_type', 'icao_aircraft_type_actual',
       'flighthistory_id', 'callsign', 'latitude', 'longitude',
       'asdiflightplan_id', 'ordinal', 'airway', 'center', 'fix', 'sector'],
      dtype='object')

In [47]:
idk2.drop('asdiflightplan_id',  axis=1, inplace = True)
idk2.drop('ordinal',  axis=1, inplace = True)

In [49]:
idk2.dropna(subset = ['scheduled_gate_departure', 'actual_gate_departure', 'scheduled_gate_arrival',  'actual_gate_arrival', 'scheduled_runway_departure', 'actual_runway_departure', 'scheduled_runway_arrival', 'actual_runway_arrival', 'scheduled_air_time', 'scheduled_block_time', 'scheduled_aircraft_type', 'icao_aircraft_type_actual'], inplace = True)

In [50]:
idk2.shape

(3141014, 25)

In [52]:
pd.set_option('display.max_rows', None)
idk2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3141014 entries, 17463 to 3664985
Data columns (total 25 columns):
 #   Column                             Dtype
---  ------                             -----
 0   flight_number                      int64
 1   departure_airport_code             object
 2   arrival_airport_code               object
 3   scheduled_gate_departure           object
 4   actual_gate_departure              object
 5   scheduled_gate_arrival             object
 6   actual_gate_arrival                object
 7   scheduled_runway_departure         object
 8   actual_runway_departure            object
 9   scheduled_runway_arrival           object
 10  actual_runway_arrival              object
 11  scheduled_air_time                 float64
 12  scheduled_block_time               float64
 13  departure_airport_timezone_offset  int64
 14  arrival_airport_timezone_offset    int64
 15  scheduled_aircraft_type            object
 16  icao_aircraft_type_actual          object
 17  flighthistory_id                   int64
 18  callsign                           object
 19  latitude                           float64
 20  longitude                          float64
 21  airway                             object
 22  center                             object
 23  fix                                object
 24  sector                             object
dtypes: float64(4), int64(4), object(17)
memory usage: 623.1+ MB

In [53]:
idk2.dtypes

flight_number                          int64
departure_airport_code                object
arrival_airport_code                  object
scheduled_gate_departure              object
actual_gate_departure                 object
scheduled_gate_arrival                object
actual_gate_arrival                   object
scheduled_runway_departure            object
actual_runway_departure               object
scheduled_runway_arrival              object
actual_runway_arrival                 object
scheduled_air_time                   float64
scheduled_block_time                 float64
departure_airport_timezone_offset      int64
arrival_airport_timezone_offset        int64
scheduled_aircraft_type               object
icao_aircraft_type_actual             object
flighthistory_id                       int64
callsign                              object
latitude                             float64
longitude                            float64
airway                                object
center                                object
fix                                   object
sector                                object
dtype: object

In [54]:
idk2[['callalpha', 'callnum']] = idk2['callsign'].str.extract(r'([A-Za-z]+)(\d+)')